### ISSUE TITLE
Implement Server API.

### ISSUE THREAD

**Issue by real-yfprojects** [real-yfprojects/ectec#18]
Implement the Server API for version 1.0.0.

# Features

- [x] Connect protocol
- [x] Store connected people
- [x] Exchange user list
- [x] Receive packages
- [x] Forward packages

# Tasks

- [x] Start `ThreadingTCPServer` in a new thread
- [x] Subclass `BasicRequestHandler`
- [x] Implement locks and thread safety
- [x] Handle Connects
- [x] Handle packages
- [x] Share packages
- [x] Handle disconnects
- [x] Share user list
- [x] Log
- [x] Handle closed connections
