### ISSUE TITLE
Implement Client API.

### ISSUE THREAD

**Issue by real-yfprojects** [real-yfprojects/ectec#22]
Implement the Client API for version 1.0.0

# Features
- [x] List of users online
- [x] send raw text messages
- [x] receive raw text messages
- [x] filter by receiver
- [x] `all` and multiple receivers

# Tasks

- [x] Implement `Package`
- [x] Implement `PackageStorage`
- [x] Implement `UserClient`
- [x] Implement `recv_bytes`
- [x] Implement `recv_command`
- [x] Implement INFO command (send)
- [x] Implement INFO command (recv)
- [x] Implement REGISTER command (send)
- [x] Implement UPDATE USERS command (recv)
- [x] Implement PACKAGE command (send)
- [x] Implement PACKAGE command (recv)
- [x] Implement `UserClient.connect`
- [x] Implement `UserClient.disconnect`
- [x] Implement use in `with` context
- [x] Implement `server` property
- [x] Implement send package
- [x] Implement receive package

**Comment by real-yfprojects** [comment]
Dammit! I accidentally deleted all the client code since I didn't commit it yet. I switched branches and didn't stash the work.

**Comment by real-yfprojects** [comment]
> Dammit! I accidentally deleted all the client code since I didn't commit it yet. I switched branches and didn't stash the work.

Luckily I recently did a backup of my drive. So I was able to retrieve the work.
