### ISSUE TITLE
TODO: Allow muliple receivers for a package

### ISSUE THREAD

**Issue by real-yfprojects** [real-yfprojects/ectec#23]
A package should be allowed to have multiple receivers. This must be enabled in

- [x] the `Package` class
- [x] the PACKAGE command
- [x] the *namedtuple* representing a package server side

.
