### ISSUE TITLE
TODO: Allow printing logs to log file.

### ISSUE THREAD

**Issue by real-yfprojects** [real-yfprojects/ectec#56]
Add a command line argument that prints the log records to a specified log file.

- [x] Cmd argument for Log file
- [x] Cmd argument for Log level
- [x] Default log file?
