### ISSUE TITLE
TODO: Implement custom chat widget.

### ISSUE THREAD

**Issue by real-yfprojects** [real-yfprojects/ectec#58]
This widget should show the messages from a chat based on the Model/View Architecture.

## Thoughts
- ListView
- ItemDelegates and stuff
- Respect and use widget's `QStyle`.
- sizeHintChanged signal
- shadows are not supported for most shapes

# Progress
- [x] Prototype
- [x] Connect to view (adjust sizeHint to view width)
- [x] list local name first in receiver list
- [x] Popup tool tips
- [x] Respect states and selection (frame color)
- [x] Signals
- [ ] Make text in bubble selectable. (no easy possibility found)
